name: Cron Download Public Images

on:
  schedule:
    - cron: "0 4-21 * * *"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download script
        run: python download.py

      - name: Repo commit
        run: |-
          git config user.name "Github Action"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Add new images"

      - name: Make «push»
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
